<?php

$redis = new Redis();
$redis->connect('127.0.0.1', 6379);


$redis->set("featured_1", '{"title": "fan fiction innit", "author": "adam", "story": "Shivering, I step out of the lashing rain and into my apartment - \"Christ, what a day\" I grumble, hanging up my soaking wet jacket. After what I\'ve been through in that society meetup, I\'m completely drained... I stumble back towards my bedroom, my head filled with witty comebacks regarding my enemies maternal figures when suddenly, I see him - lying seductively on my desk, inviting me in. At first, I think I\'m hallucinating - surely it\'s too good to be true? But no sooner does that thought cross my mind than I hear his seductive purring and whirring... My fatigue disappears - I tear across my room and throw myself in front of my desk, baring my chest and arms for him - \"I\'m ready - take me!\" I cry, as the cool air washes over me. I love my fan! 8/10 the packaging was slightly damaged though."}');
$redis->set("featured_2", '{"author": "adam", "story": "When I first caught sight of Joe Biden from across the club, I was enthralled.\n\nJoe Biden.\n\nThe Vice President.\n\nFrom Scranton, PA.\n\nI couldn\'t believe it.\n\nWe locked eyes and I thought I saw him wink at me, but I\'m pretty sure he was just grimacing as he chewed on his sandwich.\n\nWhen I returned my attention to the job I was doing, I was alarmed to find that my best friend\'s eyeballs had turned into slits and that her lips were pressed into a thin line, as she glared back at me and whispered to herself, \"He\'s staring at me, isn\'t he?\"\n\nUh, yep.\n\nI returned to the only girl in the room and made a joke about his intense stare, hoping she would find it as hilarious as I did.\n\nEventually, I chatted with a few other girlfriends in the room, pretending that Joe was a footman standing over me, holding a candelabra and dancing with me around the room, while wearing my jewels.\n\nLuckily, she is tall, so she was able to handle it pretty well, although her walk was stiff with anger, and her cheeks were rosy and red.", "title": "joe biden"}');
$redis->set("featured_3", '{"author": "adam", "story": "Deathmatch: Angus the Gardener vs Angus Gardner. Angus is favourite to win but he\'s going to face a strong challenge from Angus Gardner. The winner will go through to the final.\n\nThe Greasy Spoon: A buffet lunch for all in the Greasy Spoon bar plus a drink from the bar will be on offer.\n\nJam and Jammin: A homemade sandwich-making competition will be held in the Butchery where the winner will get a certificate to display.\n\nBooking is required.", "title": "angus the gardener VS. angus gardner"}');
$redis->save();
?>