version: "3"

x-deployment:
  stack: "web-anonnotes"
  challenge_id: "anonnotes"
  challenge_service: "web"

services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: "AFWFJHAWDAWJHASDADWAW"
      MYSQL_USER: "anon"
      MYSQL_PASSWORD: "P8e9spXP356&g5PK"
      MYSQL_DATABASE: "webapp"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442
